#: schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = "[{{.Shell}}]{{.UserName}}@{{.HostName}}: {{.PWD}}"

[palette]
os = "#ACB0BE"
closer = "p:os"
pink = "#F5C2E7"
lavender = "#B4BEFE"
blue = "#89B4FA"
red = "#F38BA8"

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  type = "upgrade"
  style = "plain"
  foreground = "p:os"
  template = "\uf019" # 

  [[blocks.segments]]
  type = "os"
  foreground = "p:os"
  style = "plain"
  template = "{{ if .WSL }}{{ end }}{{.Icon}} "

  [[blocks.segments]]
  type = "session"
  style = "plain"
  foreground = "p:blue"
  template = "{{ .UserName }}@{{ .HostName }} "

  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "p:pink"
  template = "{{ .Path }} "

    [blocks.segments.properties]
    style = "agnoster_short"
    folder_icon = "..\ue5fe.." # 
    home_icon = "~"

[[blocks]]
  type = "prompt"
  alignment = "right"
  # overflow = "hidden"

  [[blocks.segments]]
  type = "git"
  style = "plain"
  foreground = "p:lavender"
  template = "{{ if gt .Behind 0 }}\uf0799{{ .Behind }}{{ end }}{{ if gt .Ahead 0 }}\uf0792{{ .Ahead }}{{ end }}{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \uf0193 {{ .StashCount }}{{ end }}"
  # \uf0799 = 󰞙
  # \uf0792 = 󰞒
  # \uf044 = 
  # \uf046 = 
  # \uf0193 = 󰆓

    [blocks.segments.properties]
    branch_icon = "\ue725 " # 
    cherry_pick_icon = "\ue29b " # 
    commit_icon = "\uf417 " # 
    fetch_status = true
    fetch_upstream_icon = true
    merge_icon = "\ue727 " # 
    no_commits_icon = "\uf0c3 " # 
    rebase_icon = "\ue728 " # 
    revert_icon = "\uf0e2 " # 
    tag_icon = "\uf412 " # 

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:closer{{end}}",
  ]
  template = "\uf105" # 

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:closer{{end}}",
  ]
  template = "\uf105 " # 

[secondary_prompt]
  foreground = "p:closer"
  template = "\uf105\uf105 " # 

